[package]
name = "hq"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.98"
crossterm = "0.29.0"
globe = "0.2.0"
ratatui = { version = "0.29.0", features = ["unstable-widget-ref"] }
systemstat = "0.2.4"
walkdir = "2.5.0"
